# Generated by Django 3.1 on 2020-09-25 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('recommend_company', models.CharField(choices=[('1', '1 - Very Unlikely'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10 - Very Likely')], default='5', max_length=2, verbose_name='How likely would you be to recommend this company to a friend?')),
                ('what_changes', models.CharField(default='', max_length=500, verbose_name='What would you change about the product?')),
                ('was_researched', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='Yes', max_length=2, verbose_name='Did you research the product before purchasing it?')),
                ('feedback', models.CharField(blank=True, default='', max_length=500, verbose_name='Would you like to provide any other feedback?')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('started_at', models.DateTimeField(editable=False)),
                ('finished_at', models.DateTimeField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=4096)),
                ('question_type', models.CharField(choices=[('TX', 'Text'), ('OC', 'One choice'), ('MC', 'Many choices')], max_length=2)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=4096)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
        ),
    ]
