# Generated by Django 3.1 on 2020-09-25 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Opros',
        ),
    ]
