# Generated by Django 3.1 on 2020-09-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20200922_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='type',
            field=models.CharField(choices=[('TX', 'Text'), ('OC', 'One choice'), ('MC', 'Many choices')], default='TX', max_length=2),
        ),
    ]
