# Generated by Django 3.1 on 2020-09-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20200924_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('recommend_company', models.CharField(choices=[('1', '1 - Very Unlikely'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10 - Very Likely')], max_length=2, verbose_name='How likely would you be to recommend this company to a friend?')),
                ('what_changes', models.CharField(default='', max_length=500, verbose_name='What would you change about the product?')),
                ('was_researched', models.CharField(choices=[(1, 'Yes'), (0, 'No')], default='Yes', max_length=2, verbose_name='Did you research the product before purchasing it?')),
                ('feedback', models.CharField(blank=True, default='', max_length=500, verbose_name='Would you like to provide any other feedback?')),
            ],
        ),
    ]
