# Generated by Django 3.1 on 2020-09-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_opros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opros',
            name='recommend_company',
            field=models.CharField(choices=[('1', '1 - Very Unlikely'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10 - Very Likely')], default='5', max_length=2, verbose_name='How likely would you be to recommend this company to a friend?'),
        ),
    ]
