# Generated by Django 3.1 on 2020-09-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20200924_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opros',
            name='was_researched',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='Yes', max_length=2, verbose_name='Did you research the product before purchasing it?'),
        ),
    ]
